using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace PropertyResolvers.Generators;

internal sealed record ResolverArm(string TypeName, PropertyMatch Property, bool IsSource);
internal sealed record ResolverPlan(ResolverConfig Config, string Namespace, bool Typed, bool RegisterRuntime, ImmutableArray<ResolverArm> Arms)
{
    internal string ValueType => !Typed ? "string?" : Arms[0].Property.TypeName +
        (Arms.Any(arm => arm.Property.Nullable) ? "?" : "");
    internal string ReturnType => !Typed ? "string?" : Arms[0].Property.TypeName + "?";
    internal string MethodName => "Get" + Config.MethodSuffix;
}

internal static class ResolverWriter
{
    private const string Formatter = """
            private static string? FormatValue(object? value) => value is global::System.IFormattable formattable
                ? formattable.ToString(null, global::System.Globalization.CultureInfo.InvariantCulture)
                : value?.ToString();
        """;

    private static StringBuilder Header(string ns, string className) => new StringBuilder()
        .AppendLine("// <auto-generated/>").AppendLine("#nullable enable").AppendLine()
        .Append("namespace ").Append(ResolverConfiguration.EscapeNamespace(ns)).AppendLine(";").AppendLine()
        .Append("public static class ").Append(ResolverConfiguration.Escape(className)).AppendLine().AppendLine("{");

    internal static string Resolver(ResolverPlan plan)
    {
        var code = Header(plan.Namespace, plan.Config.ClassName);
        code.Append("    public static ").Append(plan.ReturnType).Append(' ').Append(plan.MethodName)
            .AppendLine("(object? obj) => obj switch").AppendLine("    {");
        foreach (var arm in plan.Arms)
        {
            code.Append("        ").Append(arm.TypeName).Append(" x => ")
                .Append(plan.Typed ? arm.Property.Expression : "FormatValue(" + arm.Property.Expression + ")").AppendLine(",");
        }
        code.AppendLine("        _ => null").AppendLine("    };").AppendLine();
        code.Append("    public static bool TryGet(object? obj, out ").Append(plan.ValueType).AppendLine(" value)")
            .AppendLine("    {").AppendLine("        switch (obj)").AppendLine("        {");
        foreach (var arm in plan.Arms)
        {
            code.Append("            case ").Append(arm.TypeName).AppendLine(" x:")
                .Append("                value = ").Append(plan.Typed ? arm.Property.Expression : "FormatValue(" + arm.Property.Expression + ")")
                .AppendLine(";").AppendLine("                return true;");
        }
        code.AppendLine("            default:").AppendLine("                value = default!;")
            .AppendLine("                return false;").AppendLine("        }").AppendLine("    }");
        // Shared compatibility formatting is also used by typed dispatch and legacy registration.
        code.AppendLine().Append("    internal static string? __GetString(object? obj) => ")
            .Append(plan.Typed ? "FormatValue(" + plan.MethodName + "(obj))" : plan.MethodName + "(obj)").AppendLine(";");
        code.AppendLine().AppendLine(Formatter).AppendLine("}");
        return code.ToString();
    }

    internal static string Dispatch(string ns, ImmutableArray<ResolverPlan> plans)
    {
        var code = Header(ns, "PropertyResolverDispatch");
        code.AppendLine("    public static bool TryResolve(string? propertyName, object? source, out string? value)")
            .AppendLine("    {");
        foreach (var plan in plans)
        {
            var resolver = "global::" + ResolverConfiguration.EscapeNamespace(ns) + "." + ResolverConfiguration.Escape(plan.Config.ClassName);
            code.Append("        if (global::System.String.Equals(propertyName, ")
                .Append(ResolverConfiguration.Literal(plan.Config.PropertyName))
                .AppendLine(", global::System.StringComparison.OrdinalIgnoreCase))").AppendLine("        {");
            if (!plan.Typed)
            {
                code.Append("            return ").Append(resolver).AppendLine(".TryGet(source, out value);");
            }
            else
            {
                code.Append("            var found = ").Append(resolver).AppendLine(".TryGet(source, out var typedValue);")
                    .AppendLine("            value = found ? FormatValue(typedValue) : null;").AppendLine("            return found;");
            }
            code.AppendLine("        }");
        }
        code.AppendLine("        value = null;").AppendLine("        return false;").AppendLine("    }")
            .AppendLine().AppendLine(Formatter).AppendLine("}");
        return code.ToString();
    }

    internal static string Registration(string ns, ImmutableArray<ResolverPlan> plans)
    {
        var code = new StringBuilder("// <auto-generated/>\n#nullable enable\n\nnamespace ")
            .Append(ResolverConfiguration.EscapeNamespace(ns)).AppendLine(";")
            .AppendLine("[global::System.Runtime.CompilerServices.CompilerGenerated]")
            .AppendLine("internal static class PropertyResolverModuleInitializer")
            .AppendLine("{").AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]")
            .AppendLine("    internal static void Initialize()")
            .AppendLine("    {");
        foreach (var plan in plans)
        {
            code.Append("        global::PropertyResolvers.Attributes.PropertyResolverRegistry.Register(")
                .Append(ResolverConfiguration.Literal(plan.Config.PropertyName)).Append(", global::")
                .Append(ResolverConfiguration.EscapeNamespace(ns)).Append('.').Append(ResolverConfiguration.Escape(plan.Config.ClassName))
                .AppendLine(".__GetString);");
        }
        return code.AppendLine("    }").AppendLine("}").ToString();
    }

    internal const string ModuleInitializerAttribute = """
        // <auto-generated/>
        namespace System.Runtime.CompilerServices;
        [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
        internal sealed class ModuleInitializerAttribute : global::System.Attribute { }
        """;
}
