<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <CompilerVisibleProperty Include="PropertyResolversNamespace" />
        <CompilerVisibleProperty Include="PropertyResolversOutput" />
        <CompilerVisibleProperty Include="PropertyResolversRegisterRuntime" />
        <ProjectReference Include="..\..\src\PropertyResolvers.Attributes\PropertyResolvers.Attributes.csproj" />
        <ProjectReference Include="..\..\src\PropertyResolvers.Generators\PropertyResolvers.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

  

</Project>
